<ItemLabel@Label>:
    font_size: '25sp'

<Container>:
    orientation: 'vertical'
    padding: 50
    spacing: 50
    text_input: text_input
    label_widget: label
    TextInput:
        id: text_input
    ItemLabel:
        id: label
        font_size: 40
        text: 'Some text'
    Carousel:
        loop: True
        AsyncImage:
            source: 'http://placehold.it/480x270.png&text=slide-1.png'
        AsyncImage:
            source: 'http://placehold.it/480x270.png&text=slide-2.png'
        AsyncImage:
            source: 'http://placehold.it/480x270.png&text=slide-3.png'
        AsyncImage:
            source: 'http://placehold.it/480x270.png&text=slide-4.png'
    Button:
        text: 'World'
        on_release:
            root.change_text()